name: Googletest Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Loki
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: |
            dependencies/benchmark-install
            dependencies/boost
            dependencies/googletest-install
        key: ${{ runner.os }}-benchmark-${{ hashFiles('**/dependencies/benchmark/CMakeLists.txt', '**/dependencies/boost/CMakeLists.txt', '**/dependencies/googletest/CMakeLists.txt') }}  # Unique key based on OS and CMake files

    - name: Configure, Build, and Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        cmake -S dependencies -B dependencies/build
        cmake --build dependencies/build -j$(nproc)

    - name: Configure, and Build Loki
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=ON -S . -B build
        cmake --build build -j$(nproc)

    - name: Test
      working-directory: build/tests/unit
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
